using OneEduDataAccess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OneEduDataAccess
{
    public class DiemChiTietEntity
    {
        public string MA_HS { get; set; }
        public string TEN_HS { get; set; }
        public short MA_GIOI_TINH { get; set; }
        public string TEN_GIOI_TINH { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public long ID_HOC_SINH { get; set; }
        public long ID_LOP { get; set; }
        public short HOC_KY { get; set; }
        public Nullable<short> ID_MON_HOC { get; set; }
        public long ID_TRUONG { get; set; }
        public Nullable<decimal> DIEM1 { get; set; }
        public string DIEM1_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM1 { get; set; }
        public string LOG_DIEM1 { get; set; }
        public Nullable<decimal> DIEM2 { get; set; }
        public string DIEM2_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM2 { get; set; }
        public string LOG_DIEM2 { get; set; }
        public Nullable<decimal> DIEM3 { get; set; }
        public string DIEM3_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM3 { get; set; }
        public string LOG_DIEM3 { get; set; }
        public Nullable<decimal> DIEM4 { get; set; }
        public string DIEM4_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM4 { get; set; }
        public string LOG_DIEM4 { get; set; }
        public Nullable<decimal> DIEM5 { get; set; }
        public string DIEM5_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM5 { get; set; }
        public string LOG_DIEM5 { get; set; }
        public Nullable<decimal> DIEM6 { get; set; }
        public string DIEM6_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM6 { get; set; }
        public string LOG_DIEM6 { get; set; }
        public Nullable<decimal> DIEM7 { get; set; }
        public string DIEM7_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM7 { get; set; }
        public string LOG_DIEM7 { get; set; }
        public Nullable<decimal> DIEM8 { get; set; }
        public string DIEM8_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM8 { get; set; }
        public string LOG_DIEM8 { get; set; }
        public Nullable<decimal> DIEM9 { get; set; }
        public string DIEM9_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM9 { get; set; }
        public string LOG_DIEM9 { get; set; }
        public Nullable<decimal> DIEM10 { get; set; }
        public string DIEM10_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM10 { get; set; }
        public string LOG_DIEM10 { get; set; }
        public Nullable<decimal> DIEM_HOC_KY { get; set; }
        public string DIEM_HOC_KY_VIEW { get; set; }
        public Nullable<decimal> DIEM_TRUNG_BINH_KY1 { get; set; }
        public string DIEM_TRUNG_BINH_KY1_VIEW { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<short> IS_DELETE { get; set; }
        public Nullable<decimal> DIEM11 { get; set; }
        public string DIEM11_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM11 { get; set; }
        public string LOG_DIEM11 { get; set; }
        public Nullable<decimal> DIEM12 { get; set; }
        public string DIEM12_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM12 { get; set; }
        public string LOG_DIEM12 { get; set; }
        public Nullable<decimal> DIEM13 { get; set; }
        public string DIEM13_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM13 { get; set; }
        public string LOG_DIEM13 { get; set; }
        public Nullable<decimal> DIEM14 { get; set; }
        public string DIEM14_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM14 { get; set; }
        public string LOG_DIEM14 { get; set; }
        public Nullable<decimal> DIEM15 { get; set; }
        public string DIEM15_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM15 { get; set; }
        public string LOG_DIEM15 { get; set; }
        public Nullable<decimal> DIEM_TRUNG_BINH_KY2 { get; set; }
        public string DIEM_TRUNG_BINH_KY2_VIEW { get; set; }
        public Nullable<decimal> DIEM_TRUNG_BINH_CN { get; set; }
        public string DIEM_TRUNG_BINH_CN_VIEW { get; set; }
        public Nullable<decimal> DIEM_TRUNG_BINH_CN_TTL { get; set; }
        public string DIEM_TRUNG_BINH_CN_TTL_VIEW { get; set; }
        public short ID_NAM_HOC { get; set; }
        public short MA_KHOI { get; set; }
        public Nullable<decimal> DIEM16 { get; set; }
        public string DIEM16_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM16 { get; set; }
        public string LOG_DIEM16 { get; set; }
        public Nullable<decimal> DIEM17 { get; set; }
        public string DIEM17_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM17 { get; set; }
        public string LOG_DIEM17 { get; set; }
        public Nullable<decimal> DIEM18 { get; set; }
        public string DIEM18_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM18 { get; set; }
        public string LOG_DIEM18 { get; set; }
        public Nullable<decimal> DIEM19 { get; set; }
        public string DIEM19_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM19 { get; set; }
        public string LOG_DIEM19 { get; set; }
        public Nullable<decimal> DIEM20 { get; set; }
        public string DIEM20_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM20 { get; set; }
        public string LOG_DIEM20 { get; set; }
        public Nullable<decimal> DIEM21 { get; set; }
        public string DIEM21_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM21 { get; set; }
        public string LOG_DIEM21 { get; set; }
        public Nullable<decimal> DIEM22 { get; set; }
        public string DIEM22_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM22 { get; set; }
        public string LOG_DIEM22 { get; set; }
        public Nullable<decimal> DIEM23 { get; set; }
        public string DIEM23_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM23 { get; set; }
        public string LOG_DIEM23 { get; set; }
        public Nullable<decimal> DIEM24 { get; set; }
        public string DIEM24_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM24 { get; set; }
        public string LOG_DIEM24 { get; set; }
        public Nullable<decimal> DIEM25 { get; set; }
        public string DIEM25_VIEW { get; set; }
        public Nullable<System.DateTime> NGAY_DIEM25 { get; set; }
        public string LOG_DIEM25 { get; set; }
        public long ID_MON_HOC_TRUONG { get; set; }
        public string TEN_MON_TRUONG { get; set; }
        public Nullable<short> IS_MIEN { get; set; }
        public string DIEMMIENG { get; set; }
        public string DIEM15P { get; set; }
        public string DIEM1T_HS1 { get; set; }
        public string DIEM1T_HS2 { get; set; }
        public string DIEMHOCKY { get; set; }
    }
}
