using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OneEduDataAccess
{
    public class TongKetDiemEntity
    {
        public long ID { get; set; }
        public string MA { get; set; }
        public string HO_TEN { get; set; }
        public string TEN { get; set; }
        public Nullable<short> THU_TU { get; set; }
        public Nullable<decimal> MON_0_Ky1 { get; set; }
        public Nullable<decimal> MON_1_Ky1 { get; set; }
        public Nullable<decimal> MON_2_Ky1 { get; set; }
        public Nullable<decimal> MON_3_Ky1 { get; set; }
        public Nullable<decimal> MON_4_Ky1 { get; set; }
        public Nullable<decimal> MON_5_Ky1 { get; set; }
        public Nullable<decimal> MON_6_Ky1 { get; set; }
        public Nullable<decimal> MON_7_Ky1 { get; set; }
        public Nullable<decimal> MON_8_Ky1 { get; set; }
        public Nullable<decimal> MON_9_Ky1 { get; set; }
        public Nullable<decimal> MON_10_Ky1 { get; set; }
        public Nullable<decimal> MON_11_Ky1 { get; set; }
        public Nullable<decimal> MON_12_Ky1 { get; set; }
        public Nullable<decimal> MON_13_Ky1 { get; set; }
        public Nullable<decimal> MON_14_Ky1 { get; set; }
        public Nullable<decimal> MON_15_Ky1 { get; set; }
        public Nullable<decimal> MON_16_Ky1 { get; set; }
        public Nullable<decimal> MON_17_Ky1 { get; set; }
        public Nullable<decimal> MON_18_Ky1 { get; set; }
        public Nullable<decimal> MON_19_Ky1 { get; set; }
        public Nullable<decimal> MON_20_Ky1 { get; set; }
        public Nullable<decimal> MON_21_Ky1 { get; set; }
        public Nullable<decimal> MON_22_Ky1 { get; set; }
        public Nullable<decimal> MON_23_Ky1 { get; set; }
        public Nullable<decimal> MON_24_Ky1 { get; set; }
        public Nullable<decimal> MON_0_Ky2 { get; set; }
        public Nullable<decimal> MON_1_Ky2 { get; set; }
        public Nullable<decimal> MON_2_Ky2 { get; set; }
        public Nullable<decimal> MON_3_Ky2 { get; set; }
        public Nullable<decimal> MON_4_Ky2 { get; set; }
        public Nullable<decimal> MON_5_Ky2 { get; set; }
        public Nullable<decimal> MON_6_Ky2 { get; set; }
        public Nullable<decimal> MON_7_Ky2 { get; set; }
        public Nullable<decimal> MON_8_Ky2 { get; set; }
        public Nullable<decimal> MON_9_Ky2 { get; set; }
        public Nullable<decimal> MON_10_Ky2 { get; set; }
        public Nullable<decimal> MON_11_Ky2 { get; set; }
        public Nullable<decimal> MON_12_Ky2 { get; set; }
        public Nullable<decimal> MON_13_Ky2 { get; set; }
        public Nullable<decimal> MON_14_Ky2 { get; set; }
        public Nullable<decimal> MON_15_Ky2 { get; set; }
        public Nullable<decimal> MON_16_Ky2 { get; set; }
        public Nullable<decimal> MON_17_Ky2 { get; set; }
        public Nullable<decimal> MON_18_Ky2 { get; set; }
        public Nullable<decimal> MON_19_Ky2 { get; set; }
        public Nullable<decimal> MON_20_Ky2 { get; set; }
        public Nullable<decimal> MON_21_Ky2 { get; set; }
        public Nullable<decimal> MON_22_Ky2 { get; set; }
        public Nullable<decimal> MON_23_Ky2 { get; set; }
        public Nullable<decimal> MON_24_Ky2 { get; set; }
        public Nullable<decimal> MON_0_CN { get; set; }
        public Nullable<decimal> MON_1_CN { get; set; }
        public Nullable<decimal> MON_2_CN { get; set; }
        public Nullable<decimal> MON_3_CN { get; set; }
        public Nullable<decimal> MON_4_CN { get; set; }
        public Nullable<decimal> MON_5_CN { get; set; }
        public Nullable<decimal> MON_6_CN { get; set; }
        public Nullable<decimal> MON_7_CN { get; set; }
        public Nullable<decimal> MON_8_CN { get; set; }
        public Nullable<decimal> MON_9_CN { get; set; }
        public Nullable<decimal> MON_10_CN { get; set; }
        public Nullable<decimal> MON_11_CN { get; set; }
        public Nullable<decimal> MON_12_CN { get; set; }
        public Nullable<decimal> MON_13_CN { get; set; }
        public Nullable<decimal> MON_14_CN { get; set; }
        public Nullable<decimal> MON_15_CN { get; set; }
        public Nullable<decimal> MON_16_CN { get; set; }
        public Nullable<decimal> MON_17_CN { get; set; }
        public Nullable<decimal> MON_18_CN { get; set; }
        public Nullable<decimal> MON_19_CN { get; set; }
        public Nullable<decimal> MON_20_CN { get; set; }
        public Nullable<decimal> MON_21_CN { get; set; }
        public Nullable<decimal> MON_22_CN { get; set; }
        public Nullable<decimal> MON_23_CN { get; set; }
        public Nullable<decimal> MON_24_CN { get; set; }
        public Nullable<decimal> TB_KY1 { get; set; }
        public Nullable<decimal> TB_KY2 { get; set; }
        public Nullable<decimal> TB_CN { get; set; }
        public Nullable<short> KIEU_MON_0 { get; set; }
        public Nullable<short> KIEU_MON_1 { get; set; }
        public Nullable<short> KIEU_MON_2 { get; set; }
        public Nullable<short> KIEU_MON_3 { get; set; }
        public Nullable<short> KIEU_MON_4 { get; set; }
        public Nullable<short> KIEU_MON_5 { get; set; }
        public Nullable<short> KIEU_MON_6 { get; set; }
        public Nullable<short> KIEU_MON_7 { get; set; }
        public Nullable<short> KIEU_MON_8 { get; set; }
        public Nullable<short> KIEU_MON_9 { get; set; }
        public Nullable<short> KIEU_MON_10 { get; set; }
        public Nullable<short> KIEU_MON_11 { get; set; }
        public Nullable<short> KIEU_MON_12 { get; set; }
        public Nullable<short> KIEU_MON_13 { get; set; }
        public Nullable<short> KIEU_MON_14 { get; set; }
        public Nullable<short> KIEU_MON_15 { get; set; }
        public Nullable<short> KIEU_MON_16 { get; set; }
        public Nullable<short> KIEU_MON_17 { get; set; }
        public Nullable<short> KIEU_MON_18 { get; set; }
        public Nullable<short> KIEU_MON_19 { get; set; }
        public Nullable<short> KIEU_MON_20 { get; set; }
        public Nullable<short> KIEU_MON_21 { get; set; }
        public Nullable<short> KIEU_MON_22 { get; set; }
        public Nullable<short> KIEU_MON_23 { get; set; }
        public Nullable<short> KIEU_MON_24 { get; set; }
        public Nullable<short> HE_SO_0  { get; set; }
        public Nullable<short> HE_SO_1  { get; set; }
        public Nullable<short> HE_SO_2  { get; set; }
        public Nullable<short> HE_SO_3  { get; set; }
        public Nullable<short> HE_SO_4  { get; set; }
        public Nullable<short> HE_SO_5  { get; set; }
        public Nullable<short> HE_SO_6  { get; set; }
        public Nullable<short> HE_SO_7  { get; set; }
        public Nullable<short> HE_SO_8  { get; set; }
        public Nullable<short> HE_SO_9  { get; set; }
        public Nullable<short> HE_SO_10 { get; set; }
        public Nullable<short> HE_SO_11 { get; set; }
        public Nullable<short> HE_SO_12 { get; set; }
        public Nullable<short> HE_SO_13 { get; set; }
        public Nullable<short> HE_SO_14 { get; set; }
        public Nullable<short> HE_SO_15 { get; set; }
        public Nullable<short> HE_SO_16 { get; set; }
        public Nullable<short> HE_SO_17 { get; set; }
        public Nullable<short> HE_SO_18 { get; set; }
        public Nullable<short> HE_SO_19 { get; set; }
        public Nullable<short> HE_SO_20 { get; set; }
        public Nullable<short> HE_SO_21 { get; set; }
        public Nullable<short> HE_SO_22 { get; set; }
        public Nullable<short> HE_SO_23 { get; set; }
        public Nullable<short> HE_SO_24 { get; set; }
        public int IS_MON_CHUYEN_0 { get; set; }
        public int IS_MON_CHUYEN_1  { get; set; }
        public int IS_MON_CHUYEN_2  { get; set; }
        public int IS_MON_CHUYEN_3  { get; set; }
        public int IS_MON_CHUYEN_4  { get; set; }
        public int IS_MON_CHUYEN_5  { get; set; }
        public int IS_MON_CHUYEN_6  { get; set; }
        public int IS_MON_CHUYEN_7  { get; set; }
        public int IS_MON_CHUYEN_8  { get; set; }
        public int IS_MON_CHUYEN_9  { get; set; }
        public int IS_MON_CHUYEN_10 { get; set; }
        public int IS_MON_CHUYEN_11 { get; set; }
        public int IS_MON_CHUYEN_12 { get; set; }
        public int IS_MON_CHUYEN_13 { get; set; }
        public int IS_MON_CHUYEN_14 { get; set; }
        public int IS_MON_CHUYEN_15 { get; set; }
        public int IS_MON_CHUYEN_16 { get; set; }
        public int IS_MON_CHUYEN_17 { get; set; }
        public int IS_MON_CHUYEN_18 { get; set; }
        public int IS_MON_CHUYEN_19 { get; set; }
        public int IS_MON_CHUYEN_20 { get; set; }
        public int IS_MON_CHUYEN_21 { get; set; }
        public int IS_MON_CHUYEN_22 { get; set; }
        public int IS_MON_CHUYEN_23 { get; set; }
        public int IS_MON_CHUYEN_24 { get; set; }
    }                                   
}
