//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAI_TAP_VE_NHA_CHI_TIET
    {
        public long ID { get; set; }
        public long ID_BTVN { get; set; }
        public short ID_MON_HOC { get; set; }
        public long ID_SACH { get; set; }
        public short BAI_SO { get; set; }
        public short TRANG_SO { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public long ID_TRUONG { get; set; }
        public string MA_CAP_HOC { get; set; }
    
        public virtual BAI_TAP_VE_NHA BAI_TAP_VE_NHA { get; set; }
    }
}
