//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CUSTOMER_TO_CUSTOMER = new HashSet<CUSTOMER_TO_CUSTOMER>();
        }
    
        public long ID { get; set; }
        public string TEN { get; set; }
        public string HO_TEN { get; set; }
        public long ID_TRUONG { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public Nullable<short> GIOI_TINH { get; set; }
        public string HO_DEM { get; set; }
        public Nullable<short> ID_NHOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_TO_CUSTOMER> CUSTOMER_TO_CUSTOMER { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
