//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANG_KY_AN
    {
        public long ID { get; set; }
        public long ID_HOC_SINH { get; set; }
        public long ID_LOP { get; set; }
        public Nullable<short> HOC_KY { get; set; }
        public short ID_NAM_HOC { get; set; }
        public long ID_TRUONG { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<long> ID_BUA_AN { get; set; }
    
        public virtual TRUONG TRUONG { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual DM_BUA_AN DM_BUA_AN { get; set; }
    }
}
