//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM_TONG_KET
    {
        public long ID_HOC_SINH { get; set; }
        public long ID_LOP { get; set; }
        public long ID_TRUONG { get; set; }
        public Nullable<decimal> TB_KY1 { get; set; }
        public Nullable<decimal> TB_KY2 { get; set; }
        public Nullable<decimal> TB_CN { get; set; }
        public Nullable<decimal> TB_CN_TTL { get; set; }
        public Nullable<short> MA_HOC_LUC_KY1 { get; set; }
        public Nullable<short> MA_HOC_LUC_KY2 { get; set; }
        public Nullable<short> MA_HOC_LUC_CA_NAM { get; set; }
        public Nullable<short> MA_HOC_LUC_CA_NAM_TTL { get; set; }
        public Nullable<short> MA_HANH_KIEM_KY1 { get; set; }
        public Nullable<short> MA_HANH_KIEM_KY2 { get; set; }
        public Nullable<short> MA_HANH_KIEM_CA_NAM { get; set; }
        public Nullable<short> MA_HANH_KIEM_CA_NAM_TTL { get; set; }
        public Nullable<short> MA_DANH_HIEU_KY1 { get; set; }
        public Nullable<short> MA_DANH_HIEU_KY2 { get; set; }
        public Nullable<short> MA_DANH_HIEU_CN { get; set; }
        public Nullable<bool> IS_LEN_LOP { get; set; }
        public Nullable<bool> IS_TOT_NGHIEP { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public short ID_NAM_HOC { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
