//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHA_CUNG_CAP_THUC_PHAM
    {
        public long ID { get; set; }
        public string TEN { get; set; }
        public string DIA_CHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string MA_SO_THUE { get; set; }
        public Nullable<short> ID_NGAN_HANG { get; set; }
        public string SO_TAI_KHOAN { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<long> ID_TRUONG { get; set; }
    
        public virtual DM_NGAN_HANG DM_NGAN_HANG { get; set; }
    }
}
