//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SACH_NOI_DUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_SACH_NOI_DUNG()
        {
            this.DM_SACH_CHI_TIET = new HashSet<DM_SACH_CHI_TIET>();
        }
    
        public long ID { get; set; }
        public long ID_SACH { get; set; }
        public string TEN_BAI_HOC { get; set; }
        public string SO_TRANGS { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public short ID_KHOI { get; set; }
        public short ID_MON_HOC { get; set; }
        public Nullable<short> THU_TU { get; set; }
    
        public virtual DM_SACH DM_SACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_SACH_CHI_TIET> DM_SACH_CHI_TIET { get; set; }
    }
}
