//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_XA_PHUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_XA_PHUONG()
        {
            this.HOC_SINH = new HashSet<HOC_SINH>();
            this.TRUONGs = new HashSet<TRUONG>();
        }
    
        public long MA { get; set; }
        public short MA_TINH { get; set; }
        public short MA_HUYEN { get; set; }
        public string TEN { get; set; }
        public Nullable<long> THU_TU { get; set; }
    
        public virtual DM_QUAN_HUYEN DM_QUAN_HUYEN { get; set; }
        public virtual DM_TINH_THANH DM_TINH_THANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH> HOC_SINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUONG> TRUONGs { get; set; }
    }
}
