//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAO_VIEN()
        {
            this.GV_LOP_MON = new HashSet<GV_LOP_MON>();
            this.LOPs = new HashSet<LOP>();
            this.LOP_MON = new HashSet<LOP_MON>();
            this.PHIEU_NHAP_KHO = new HashSet<PHIEU_NHAP_KHO>();
            this.PHIEU_XUAT_KHO = new HashSet<PHIEU_XUAT_KHO>();
            this.TO_GIAO_VIEN_GV = new HashSet<TO_GIAO_VIEN_GV>();
        }
    
        public long ID { get; set; }
        public string TEN { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public Nullable<short> MA_GIOI_TINH { get; set; }
        public string DIA_CHI { get; set; }
        public string EMAIL { get; set; }
        public long ID_TRUONG { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<short> MA_TRANG_THAI { get; set; }
        public string HO_DEM { get; set; }
        public string HO_TEN { get; set; }
        public Nullable<short> THU_TU { get; set; }
        public Nullable<short> ID_CHUC_VU { get; set; }
        public string ZALO_CODE { get; set; }
        public Nullable<System.DateTime> NGAY_GUI_OTP { get; set; }
        public Nullable<short> OTP_COUNTER { get; set; }
    
        public virtual DM_CHUC_VU DM_CHUC_VU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_LOP_MON> GV_LOP_MON { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        public virtual GIOI_TINH GIOI_TINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_MON> LOP_MON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_NHAP_KHO> PHIEU_NHAP_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_XUAT_KHO> PHIEU_XUAT_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO_GIAO_VIEN_GV> TO_GIAO_VIEN_GV { get; set; }
    }
}
