//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_LOP_MON
    {
        public long ID_GIAO_VIEN { get; set; }
        public long ID_LOP { get; set; }
        public short ID_MON { get; set; }
        public short ID_HOCKY { get; set; }
        public Nullable<short> TRANG_THAI { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
    }
}
