//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA_SO_THEO_LOP
    {
        public long ID { get; set; }
        public long ID_TRUONG { get; set; }
        public long ID_LOP { get; set; }
        public Nullable<System.DateTime> NGAY_KHOA { get; set; }
        public Nullable<short> NAM_HOC { get; set; }
        public Nullable<short> GIAI_DOAN { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public Nullable<short> HOC_KY { get; set; }
        public Nullable<long> NGUOI_KHOA { get; set; }
        public string MA_CAP_HOC { get; set; }
    }
}
