//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOI()
        {
            this.CHAM_AN = new HashSet<CHAM_AN>();
            this.CHUYEN_CAN = new HashSet<CHUYEN_CAN>();
            this.DIEM_CHI_TIET = new HashSet<DIEM_CHI_TIET>();
            this.DM_BUA_AN = new HashSet<DM_BUA_AN>();
            this.HOC_PHI_DOT_THU_LOP = new HashSet<HOC_PHI_DOT_THU_LOP>();
            this.HOC_PHI_PHIEU_THU_HOC_SINH = new HashSet<HOC_PHI_PHIEU_THU_HOC_SINH>();
            this.HOC_SINH = new HashSet<HOC_SINH>();
            this.LOPs = new HashSet<LOP>();
            this.NANG_LUONG_TRONG_NGAY = new HashSet<NANG_LUONG_TRONG_NGAY>();
            this.NHOM_TUOI_MN = new HashSet<NHOM_TUOI_MN>();
            this.NHU_CAU_NANG_LUONG = new HashSet<NHU_CAU_NANG_LUONG>();
            this.NHU_CAU_NANG_LUONG_TRUONG = new HashSet<NHU_CAU_NANG_LUONG_TRUONG>();
            this.SUAT_AN_CHI_TIET = new HashSet<SUAT_AN_CHI_TIET>();
            this.SUAT_AN = new HashSet<SUAT_AN>();
            this.THUC_DON_CHI_TIET = new HashSet<THUC_DON_CHI_TIET>();
            this.THUC_DON = new HashSet<THUC_DON>();
        }
    
        public short MA { get; set; }
        public string TEN { get; set; }
        public Nullable<short> MA_LOAI_LOP_GDTX { get; set; }
        public Nullable<int> THU_TU { get; set; }
        public Nullable<bool> IS_MN { get; set; }
        public Nullable<bool> IS_TH { get; set; }
        public Nullable<bool> IS_THCS { get; set; }
        public Nullable<bool> IS_THPT { get; set; }
        public Nullable<bool> IS_GDTX { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAM_AN> CHAM_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYEN_CAN> CHUYEN_CAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM_CHI_TIET> DIEM_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_BUA_AN> DM_BUA_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_PHI_DOT_THU_LOP> HOC_PHI_DOT_THU_LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_PHI_PHIEU_THU_HOC_SINH> HOC_PHI_PHIEU_THU_HOC_SINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH> HOC_SINH { get; set; }
        public virtual LOAI_LOP_GDTX LOAI_LOP_GDTX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NANG_LUONG_TRONG_NGAY> NANG_LUONG_TRONG_NGAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHOM_TUOI_MN> NHOM_TUOI_MN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHU_CAU_NANG_LUONG> NHU_CAU_NANG_LUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHU_CAU_NANG_LUONG_TRUONG> NHU_CAU_NANG_LUONG_TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUAT_AN_CHI_TIET> SUAT_AN_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUAT_AN> SUAT_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUC_DON_CHI_TIET> THUC_DON_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUC_DON> THUC_DON { get; set; }
    }
}
