//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_AN
    {
        public long ID { get; set; }
        public decimal ID_NHOM_TUOI_MN { get; set; }
        public long ID_BUA_AN { get; set; }
        public long ID_THUC_DON { get; set; }
        public long ID_TRUONG { get; set; }
        public short ID_NAM_HOC { get; set; }
        public short THANG { get; set; }
        public Nullable<bool> NGAY1 { get; set; }
        public Nullable<bool> NGAY2 { get; set; }
        public Nullable<bool> NGAY3 { get; set; }
        public Nullable<bool> NGAY4 { get; set; }
        public Nullable<bool> NGAY5 { get; set; }
        public Nullable<bool> NGAY6 { get; set; }
        public Nullable<bool> NGAY7 { get; set; }
        public Nullable<bool> NGAY8 { get; set; }
        public Nullable<bool> NGAY9 { get; set; }
        public Nullable<bool> NGAY10 { get; set; }
        public Nullable<bool> NGAY11 { get; set; }
        public Nullable<bool> NGAY12 { get; set; }
        public Nullable<bool> NGAY13 { get; set; }
        public Nullable<bool> NGAY14 { get; set; }
        public Nullable<bool> NGAY15 { get; set; }
        public Nullable<bool> NGAY16 { get; set; }
        public Nullable<bool> NGAY17 { get; set; }
        public Nullable<bool> NGAY18 { get; set; }
        public Nullable<bool> NGAY19 { get; set; }
        public Nullable<bool> NGAY20 { get; set; }
        public Nullable<bool> NGAY21 { get; set; }
        public Nullable<bool> NGAY22 { get; set; }
        public Nullable<bool> NGAY23 { get; set; }
        public Nullable<bool> NGAY24 { get; set; }
        public Nullable<bool> NGAY25 { get; set; }
        public Nullable<bool> NGAY26 { get; set; }
        public Nullable<bool> NGAY27 { get; set; }
        public Nullable<bool> NGAY28 { get; set; }
        public Nullable<bool> NGAY29 { get; set; }
        public Nullable<bool> NGAY30 { get; set; }
        public Nullable<bool> NGAY31 { get; set; }
        public Nullable<long> TONG_BUA_AN { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
    
        public virtual DM_BUA_AN DM_BUA_AN { get; set; }
        public virtual NHOM_TUOI_MN NHOM_TUOI_MN { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
    }
}
