//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_MON
    {
        public long ID_LOP { get; set; }
        public Nullable<short> ID_MON { get; set; }
        public short HOC_KY { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<long> ID_GIAO_VIEN { get; set; }
        public long ID_MON_TRUONG { get; set; }
        public Nullable<short> SO_COT_DIEM_MIENG { get; set; }
        public Nullable<short> SO_COT_DIEM_15P { get; set; }
        public Nullable<short> SO_COT_DIEM_1T_HS1 { get; set; }
        public Nullable<short> SO_COT_DIEM_1T_HS2 { get; set; }
        public Nullable<bool> IS_MON_CHUYEN { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
        public virtual MON_HOC_TRUONG MON_HOC_TRUONG { get; set; }
    }
}
