//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_NX_DINH_KY
    {
        public long ID { get; set; }
        public string MA { get; set; }
        public string NOI_DUNG { get; set; }
        public short MA_LOAI_NX { get; set; }
        public Nullable<long> THU_TU { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public long ID_TRUONG { get; set; }
    
        public virtual DM_LOAI_NX DM_LOAI_NX { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
