//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ZALO_GV
    {
        public long ID { get; set; }
        public string SDT_GV { get; set; }
        public string ZALO_USER_ID { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<System.DateTime> NGAY_TRUY_CAP { get; set; }
        public Nullable<short> ID_VAI_TRO { get; set; }
        public string SDT_NHAN_SMS { get; set; }
        public string MA_XAC_NHAN { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    }
}
