//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG_MENU
    {
        public long ID_NGUOI_DUNG { get; set; }
        public long ID_TRUONG { get; set; }
        public long ID_MENU { get; set; }
        public Nullable<short> TRANG_THAI { get; set; }
        public Nullable<bool> IS_THEM { get; set; }
        public Nullable<bool> IS_XEM { get; set; }
        public Nullable<bool> IS_SUA { get; set; }
        public Nullable<bool> IS_XOA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public long ID { get; set; }
        public bool IS_DELETE { get; set; }
        public Nullable<bool> IS_SEND_SMS { get; set; }
        public Nullable<bool> IS_VIEW_INFOR { get; set; }
        public Nullable<bool> IS_EXPORT { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
