//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_TUOI_MN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOM_TUOI_MN()
        {
            this.DM_BUA_AN = new HashSet<DM_BUA_AN>();
            this.LICH_AN = new HashSet<LICH_AN>();
            this.NHU_CAU_NANG_LUONG = new HashSet<NHU_CAU_NANG_LUONG>();
            this.NHU_CAU_NANG_LUONG_TRUONG = new HashSet<NHU_CAU_NANG_LUONG_TRUONG>();
            this.SUAT_AN = new HashSet<SUAT_AN>();
            this.THUC_DON = new HashSet<THUC_DON>();
        }
    
        public decimal MA { get; set; }
        public string TEN { get; set; }
        public Nullable<short> MA_KHOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_BUA_AN> DM_BUA_AN { get; set; }
        public virtual KHOI KHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_AN> LICH_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHU_CAU_NANG_LUONG> NHU_CAU_NANG_LUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHU_CAU_NANG_LUONG_TRUONG> NHU_CAU_NANG_LUONG_TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUAT_AN> SUAT_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUC_DON> THUC_DON { get; set; }
    }
}
