//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_NHAP_KHO_DETAIL
    {
        public long ID { get; set; }
        public long ID_PHIEU_NHAP { get; set; }
        public short ID_NHOM_THUC_PHAM { get; set; }
        public long ID_THUC_PHAM { get; set; }
        public long ID_TRUONG { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP_KHO { get; set; }
        public Nullable<short> DON_VI_TINH { get; set; }
        public Nullable<decimal> SO_LUONG { get; set; }
        public Nullable<decimal> DON_GIA { get; set; }
        public Nullable<decimal> TONG_GIA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
    
        public virtual DM_DON_VI_TINH DM_DON_VI_TINH { get; set; }
        public virtual DM_NHOM_THUC_PHAM DM_NHOM_THUC_PHAM { get; set; }
        public virtual DM_THUC_PHAM DM_THUC_PHAM { get; set; }
        public virtual PHIEU_NHAP_KHO PHIEU_NHAP_KHO { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
