//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_KE_HS_THANG
    {
        public long ID { get; set; }
        public long ID_TRUONG { get; set; }
        public short ID_KHOI { get; set; }
        public long ID_NAM_HOC { get; set; }
        public long ID_LOP { get; set; }
        public short THANG { get; set; }
        public Nullable<short> TONG_SO { get; set; }
        public Nullable<short> DANG_KY { get; set; }
        public Nullable<short> KHONG_DANG_KY { get; set; }
    }
}
