//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_GIAO_VIEN_GV
    {
        public long ID { get; set; }
        public long ID_TO { get; set; }
        public long ID_GIAO_VIEN { get; set; }
        public long ID_TRUONG { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual TO_GIAO_VIEN TO_GIAO_VIEN { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
