//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneEduDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRUONG()
        {
            this.CAP_TIN_TRUONG = new HashSet<CAP_TIN_TRUONG>();
            this.CAU_HINH_CA_HOC = new HashSet<CAU_HINH_CA_HOC>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.CUSTOMER_TO = new HashSet<CUSTOMER_TO>();
            this.CUSTOMER_TO_CUSTOMER = new HashSet<CUSTOMER_TO_CUSTOMER>();
            this.CHAM_AN = new HashSet<CHAM_AN>();
            this.CHUYEN_CAN = new HashSet<CHUYEN_CAN>();
            this.DANG_KY_AN = new HashSet<DANG_KY_AN>();
            this.DANH_GIA_DINH_KY_TH = new HashSet<DANH_GIA_DINH_KY_TH>();
            this.DIEM_CHI_TIET = new HashSet<DIEM_CHI_TIET>();
            this.DIEM_TONG_KET = new HashSet<DIEM_TONG_KET>();
            this.DM_BUA_AN = new HashSet<DM_BUA_AN>();
            this.GIAO_VIEN = new HashSet<GIAO_VIEN>();
            this.HOC_PHI_DOT_THU = new HashSet<HOC_PHI_DOT_THU>();
            this.HOC_PHI_DOT_THU_LOP = new HashSet<HOC_PHI_DOT_THU_LOP>();
            this.HOC_PHI_PHIEU_THU_HOC_SINH = new HashSet<HOC_PHI_PHIEU_THU_HOC_SINH>();
            this.HOC_SINH = new HashSet<HOC_SINH>();
            this.KHO_THUC_PHAM = new HashSet<KHO_THUC_PHAM>();
            this.LICH_AN = new HashSet<LICH_AN>();
            this.LOG_USER = new HashSet<LOG_USER>();
            this.LOPs = new HashSet<LOP>();
            this.MA_NX_DINH_KY = new HashSet<MA_NX_DINH_KY>();
            this.NGUOI_DUNG_MENU = new HashSet<NGUOI_DUNG_MENU>();
            this.NGUOI_DUNG_TRUONG = new HashSet<NGUOI_DUNG_TRUONG>();
            this.NHU_CAU_NANG_LUONG_TRUONG = new HashSet<NHU_CAU_NANG_LUONG_TRUONG>();
            this.PHIEU_NHAP_KHO = new HashSet<PHIEU_NHAP_KHO>();
            this.PHIEU_NHAP_KHO_DETAIL = new HashSet<PHIEU_NHAP_KHO_DETAIL>();
            this.PHIEU_XUAT_KHO = new HashSet<PHIEU_XUAT_KHO>();
            this.PHIEU_XUAT_KHO_DETAIL = new HashSet<PHIEU_XUAT_KHO_DETAIL>();
            this.SUAT_AN = new HashSet<SUAT_AN>();
            this.SUAT_AN_CHI_TIET = new HashSet<SUAT_AN_CHI_TIET>();
            this.TIN_NHAN = new HashSet<TIN_NHAN>();
            this.TIN_TUC = new HashSet<TIN_TUC>();
            this.TO_GIAO_VIEN = new HashSet<TO_GIAO_VIEN>();
            this.TO_GIAO_VIEN_GV = new HashSet<TO_GIAO_VIEN_GV>();
            this.THUC_DON = new HashSet<THUC_DON>();
            this.THUC_DON_CHI_TIET = new HashSet<THUC_DON_CHI_TIET>();
        }
    
        public long ID { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string BRAND_NAME_VIETTEL { get; set; }
        public string DIA_CHI { get; set; }
        public string DIEN_THOAI { get; set; }
        public string EMAIL { get; set; }
        public string HIEU_TRUONG { get; set; }
        public string DIEN_THOAI_HT { get; set; }
        public string EMAIL_HT { get; set; }
        public string DIEN_THOAI_NLH { get; set; }
        public Nullable<bool> IS_TH { get; set; }
        public Nullable<bool> IS_THCS { get; set; }
        public Nullable<bool> IS_THPT { get; set; }
        public Nullable<bool> IS_GDTX { get; set; }
        public bool TRANG_THAI { get; set; }
        public Nullable<short> MA_GOI_TIN { get; set; }
        public Nullable<long> SO_HS_DANG_KY { get; set; }
        public Nullable<long> SO_HS_DUOC_MIEN { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<long> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<long> NGUOI_SUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<bool> IS_MN { get; set; }
        public Nullable<bool> IS_TRUONG_CHUYEN { get; set; }
        public Nullable<short> MA_TINH_THANH { get; set; }
        public Nullable<short> MA_QUAN_HUYEN { get; set; }
        public Nullable<long> MA_XA_PHUONG { get; set; }
        public Nullable<short> PHAN_TRAM_VUOT_HAN_MUC { get; set; }
        public Nullable<bool> IS_ACTIVE_SMS { get; set; }
        public Nullable<bool> IS_SAN_QUY_TIN_NAM { get; set; }
        public string BRAND_NAME_MOBI { get; set; }
        public string BRAND_NAME_VINA { get; set; }
        public string BRAND_NAME_VNM { get; set; }
        public string BRAND_NAME_GTEL { get; set; }
        public string CP_VIETTEL { get; set; }
        public string CP_MOBI { get; set; }
        public string CP_VINA { get; set; }
        public string CP_VNM { get; set; }
        public string CP_GTEL { get; set; }
        public Nullable<short> ID_DOI_TAC { get; set; }
        public Nullable<long> TONG_TIN_CAP { get; set; }
        public Nullable<long> TONG_TIN_DA_DUNG { get; set; }
        public string CP_VIETTEL_BACKUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_TIN_TRUONG> CAP_TIN_TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAU_HINH_CA_HOC> CAU_HINH_CA_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_TO> CUSTOMER_TO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_TO_CUSTOMER> CUSTOMER_TO_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAM_AN> CHAM_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYEN_CAN> CHUYEN_CAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANG_KY_AN> DANG_KY_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA_DINH_KY_TH> DANH_GIA_DINH_KY_TH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM_CHI_TIET> DIEM_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM_TONG_KET> DIEM_TONG_KET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_BUA_AN> DM_BUA_AN { get; set; }
        public virtual DM_QUAN_HUYEN DM_QUAN_HUYEN { get; set; }
        public virtual DM_TINH_THANH DM_TINH_THANH { get; set; }
        public virtual DM_XA_PHUONG DM_XA_PHUONG { get; set; }
        public virtual DOI_TAC DOI_TAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAO_VIEN> GIAO_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_PHI_DOT_THU> HOC_PHI_DOT_THU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_PHI_DOT_THU_LOP> HOC_PHI_DOT_THU_LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_PHI_PHIEU_THU_HOC_SINH> HOC_PHI_PHIEU_THU_HOC_SINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH> HOC_SINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO_THUC_PHAM> KHO_THUC_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_AN> LICH_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_USER> LOG_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_NX_DINH_KY> MA_NX_DINH_KY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOI_DUNG_MENU> NGUOI_DUNG_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOI_DUNG_TRUONG> NGUOI_DUNG_TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHU_CAU_NANG_LUONG_TRUONG> NHU_CAU_NANG_LUONG_TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_NHAP_KHO> PHIEU_NHAP_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_NHAP_KHO_DETAIL> PHIEU_NHAP_KHO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_XUAT_KHO> PHIEU_XUAT_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_XUAT_KHO_DETAIL> PHIEU_XUAT_KHO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUAT_AN> SUAT_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUAT_AN_CHI_TIET> SUAT_AN_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIN_NHAN> TIN_NHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIN_TUC> TIN_TUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO_GIAO_VIEN> TO_GIAO_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO_GIAO_VIEN_GV> TO_GIAO_VIEN_GV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUC_DON> THUC_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUC_DON_CHI_TIET> THUC_DON_CHI_TIET { get; set; }
        public virtual GOI_TIN GOI_TIN { get; set; }
    }
}
